version: '3'
services:
  stockmarket-manager:
    build: ./extras/docker
    volumes:
     - .:/stockmarket-manager
     - maven-volume:/root/.m2
    network_mode: "host"
  stockmarket-manager-bd:
    image: "postgres:12"
    restart: always
    ports:
     - "5432:5432"
    volumes:
     - ./extras/database/ddl.sql:/docker-entrypoint-initdb.d/1-ddl.sql
     - ./extras/database/populate-setores-acoes-empresas.sql:/docker-entrypoint-initdb.d/2-populate-setores-acoes-empresas.sql
     - ./extras/database/populate-proventos.sql:/docker-entrypoint-initdb.d/3-populate-proventos.sql
    environment:
     - POSTGRES_USER=bruno.mori  
     - POSTGRES_PASSWORD=123456
     - POSTGRES_DB=bolsa_valores
    network_mode: "host"
volumes:
  maven-volume: